version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appsoft
    ports:
      - 3306:3306
  backend:
    image: cosminlucian/adcost-backend:1.0.0
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
  frontend:
    image:
    restart: always
    environment:
      - API=
    ports:
      - 80:80

